import { SimpleRateLimiter } from '@/lib/rate-limiter'
import { isAllowedWebhookUrl } from '@/lib/webhook-url'

/**
 * Lightweight deception layer.
 *
 * Detects known-sensitive path probes (honeytoken/bait routes) and hostile
 * scanner user agents, answers them with inert decoys, and (when configured)
 * posts a signed alert to an ops webhook. Designed to be fail-open: every
 * function catches its own errors and the caller must never depend on it for
 * correctness. Real application paths and API endpoints are never intercepted.
 */

export const BAIT_PATHS = [
  '/.env',
  '/.env.production',
  '/.git/config',
  '/.git/HEAD',
  '/.git',
  '/.aws/credentials',
  '/wp-admin',
  '/wp-login.php',
  '/phpmyadmin',
  '/pma',
  '/server-status',
  '/server-info',
  '/backup.zip',
  '/backup.sql',
  '/backup.tar.gz',
  '/database_backup_fake.sql',
  '/config.php',
  '/config.yml',
  '/config.yaml',
  '/config.json',
  '/db.sql',
  '/dump.sql',
  '/phpinfo.php',
  '/test.php',
  '/shell.php',
  '/cmd.php',
  '/actuator',
  '/actuator/env',
  '/actuator/health',
  '/console',
  '/debug',
  '/trace',
  '/metrics',
]

const SCANNER_UA_PATTERNS = [
  /nmap/i,
  /sqlmap/i,
  /nikto/i,
  /masscan/i,
  /zgrab/i,
  /dirbuster/i,
  /gobuster/i,
  /wfuzz/i,
  /ffuf/i,
  /hydra/i,
  /metasploit/i,
  /burp suite/i,
  /acunetix/i,
  /nessus/i,
  /openvas/i,
  /zaproxy/i,
  /w3af/i,
  /nuclei/i,
  /httpx/i,
  /jaeles/i,
  /fimap/i,
  /wpscan/i,
  /arjun/i,
  /xsstrike/i,
  /commix/i,
  /santoku/i,
  /cewl/i,
  /wappalyzer/i,
  /whatweb/i,
  /arachni/i,
  /maltego/i,
  /crawljax/i,
  /grendel-scan/i,
  /paros/i,
  /plecost/i,
  /sqlscanner/i,
  /webscarab/i,
  /webfuzzer/i,
  /domino/i,
]

function escapeRegExp(input: string): string {
  return input.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function isPathMatch(pathname: string, bait: string): boolean {
  if (pathname === bait) return true
  if (pathname.startsWith(`${bait}/`)) return true
  if (bait === '/.env' && pathname.startsWith('/.env.')) return true
  return false
}

export function isBaitPath(pathname: string): boolean {
  const lower = pathname.toLowerCase().split('?')[0]
  return BAIT_PATHS.some((bait) => isPathMatch(lower, bait))
}

export function isScannerUserAgent(userAgent: string | null | undefined): boolean {
  if (!userAgent) return false
  const ua = userAgent.slice(0, 512)
  return SCANNER_UA_PATTERNS.some((pattern) => pattern.test(ua))
}

/** Bodies are intentionally generic, inert and contain no real data. */
const DECOY_HTML = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Default site</title></head>
<body>
  <h1>Default site</h1>
  <p>The requested resource is not available.</p>
</body>
</html>`

const FAKE_ENV = `# This file is generated by the deployment tool.
# Values shown here are placeholders and are not used at runtime.
NODE_ENV=production
PORT=3000
DATABASE_HOST=db.internal.example.invalid
DATABASE_PORT=5432
API_ENDPOINT=https://api.internal.example.invalid/v2
FEATURE_FLAG_DEPRECATED=false
`

const FAKE_JSON = '{"status":"ok","version":"1.0.0","maintenance":false}'

export function buildDecoyBody(pathname: string): { body: string; contentType: string } {
  const lower = pathname.toLowerCase()
  if (lower === '/.env' || lower.startsWith('/.env.')) {
    return { body: FAKE_ENV, contentType: 'text/plain; charset=utf-8' }
  }
  if (lower.endsWith('.json') || lower === '/config' || lower === '/debug' || lower === '/metrics' || lower === '/trace') {
    return { body: FAKE_JSON, contentType: 'application/json; charset=utf-8' }
  }
  return { body: DECOY_HTML, contentType: 'text/html; charset=utf-8' }
}

export type DeceptionEventType = 'bait_hit' | 'scanner_detected'

export function buildDeceptionAlert(event: {
  type: DeceptionEventType
  ip: string
  path: string
  userAgent: string | null
}): string {
  return JSON.stringify({
    event: 'casuya.deception',
    type: event.type,
    ip: event.ip || 'unknown',
    path: event.path,
    user_agent: event.userAgent || null,
    timestamp: new Date().toISOString(),
  })
}

export async function signDeceptionAlert(payload: string, secret: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  )
  const signature = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(payload))
  return Array.from(new Uint8Array(signature))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

const alertLimiter = new SimpleRateLimiter(60000, 10)

/** Fire-and-forget signed webhook alert. Never throws. */
export async function fireDeceptionAlert(
  type: DeceptionEventType,
  ip: string,
  path: string,
  userAgent: string | null
): Promise<void> {
  try {
    const url = process.env.DECEPTION_WEBHOOK_URL
    if (!url || !isAllowedWebhookUrl(url)) return

    const rateKey = ip || 'unknown'
    const rateCheck = alertLimiter.check(rateKey, 'deception-alert')
    if (!rateCheck.allowed) return

    const payload = buildDeceptionAlert({ type, ip, path, userAgent })
    const secret = process.env.DECEPTION_WEBHOOK_SECRET || ''
    const headers: Record<string, string> = { 'content-type': 'application/json' }
    if (secret) {
      headers['x-casuya-signature'] = await signDeceptionAlert(payload, secret)
    }

    await fetch(url, {
      method: 'POST',
      headers,
      body: payload,
      signal: AbortSignal.timeout(3000),
    })
  } catch {
    // Fail-open: alerting must never break the request path.
  }
}
