-- Web Vitals Persistence
CREATE TABLE IF NOT EXISTS web_vitals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  lab_id UUID REFERENCES labs(id) ON DELETE SET NULL,
  metric_name TEXT NOT NULL CHECK (metric_name IN ('LCP', 'INP', 'CLS', 'TTFB', 'FID')),
  metric_value NUMERIC(10,2) NOT NULL,
  rating TEXT CHECK (rating IN ('good', 'needs-improvement', 'poor')),
  page_url TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_web_vitals_student ON web_vitals(student_id, created_at);
CREATE INDEX IF NOT EXISTS idx_web_vitals_metric ON web_vitals(metric_name, created_at);
