import { describe, expect, it } from 'vitest'
import { NextRequest } from 'next/server'
import { middleware } from '../../middleware'

describe('deception middleware', () => {
  it('answers .env probes with an inert decoy, not real data', async () => {
    const req = new NextRequest('http://localhost/.env', {
      headers: { 'x-forwarded-for': '203.0.113.10' },
    })
    const res = await middleware(req)
    expect(res.status).toBe(200)
    const body = await res.text()
    expect(body).toContain('This file is generated by the deployment tool')
    expect(body).not.toContain('LAB_CONTENT_API_KEY')
  })

  it('answers scanner-style paths with a generic html decoy', async () => {
    const req = new NextRequest('http://localhost/wp-login.php')
    const res = await middleware(req)
    expect(res.status).toBe(200)
    const body = await res.text()
    expect(body).toContain('<h1>Default site</h1>')
  })

  it('rejects non-GET probes without leaking anything', async () => {
    const req = new NextRequest('http://localhost/phpmyadmin', { method: 'POST' })
    const res = await middleware(req)
    expect(res.status).toBe(404)
  })

  it('keeps serving real endpoints normally, even with a scanner user agent', async () => {
    const req = new NextRequest('http://localhost/api/v1/public', {
      headers: { 'user-agent': 'sqlmap/1.7' },
    })
    const res = await middleware(req)
    expect(res.status).toBe(200)
  })

  it('never intercepts the labs pages', async () => {
    const req = new NextRequest('http://localhost/labs/some-lab')
    const res = await middleware(req)
    expect(res.status).toBe(200)
  })
})
